---
- name: Create the bare repo
  command: "git init --bare \"{{ gitpush_repo_path }}\""

- name: Creating the post-receive hook
  template:
    src: post-receive.j2
    dest: "{{ gitpush_repo_path }}/hooks/post-receive"
    mode: u=rwx,g=rwx,o=
